{% set name = "textgrad" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/textgrad-{{ version }}.tar.gz
  sha256: 747779cb3af36d300813db4f78b5bada29ba44a8414f2c4b863f72e3bc7de185

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - openai >=1.23.6
    - tenacity >=8.2.3
    - python-dotenv >=1.0.0
    - pandas >=1.5.3
    - platformdirs >=3.11.0
    - datasets >=2.14.6
    - diskcache >=5.6.3
    - python-graphviz >=0.20.3
    - gdown >=5.2.0

test:
  imports:
    - textgrad
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zou-group/textgrad
  summary: "Automatic ''Differentiation'' via Text -- using large language models to backpropagate textual gradients."
  license: MIT
  license_file: LICENSE
  description: |
    [![Arxiv](https://img.shields.io/badge/arXiv-2406.07496-B31B1B.svg)](https://arxiv.org/abs/2406.07496)

    ## TextGrad: Automatic ''Differentiation'' via Text

    An autograd engine -- for textual gradients! 

    TextGrad is a powerful framework  building automatic ``differentiation'' via text.
    TextGrad implements backpropagation through text feedback provided by LLMs, strongly building on the gradient metaphor

    We provide a simple and intuitive API that allows you to define your own loss functions and optimize them using text feedback.
    This API is similar to the Pytorch API, making it simple to adapt to your usecases.

    ![Analogy with Torch](https://github.com/zou-group/textgrad/blob/main/assets/analogy.png?raw=true)

    PyPI: [https://pypi.org/project/{{ name | lower }}/](https://pypi.org/project/{{ name | lower }}/)
    ---
    :fire: The conda-forge recipe was generated with [Conda-Forger App](https://sugatoray-conda-forger.streamlit.app/).

  doc_url: http://textgrad.com/
  dev_url: https://github.com/zou-group/textgrad

extra:
  recipe-maintainers:
    - sugatoray
